# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e8b9a787b0827785f205cd32ff941e76d584acb70bfde3c0ba1f45fc1742a2d2c1a1bf142e7de8d9b2b16dd7b8e266d2f3f06ba124de117ad5485a507578cec

test:
  secret_key_base: 75cd2485c4489f9c3aff1533944b8bc947f2a8bc3ab61f2bdc709be7827584f1c726793299ee0efe82dc1797498bb293d528cdaffc3844f421d6d0d4666ff6e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
